### ISSUE TITLE
Additional commands for deploy hook

### ISSUE THREAD

**Issue by jangrewe** [silkeh/pdns_api.sh#13]
Hi, thanks for your work on this!
I have the issue that LE seems to always query my slave NS, and that one doesn't seem to update that fast. An easy fix for this, besides setting an absurdly high wait time, would be triggering a NOTIFY for the respective domain.

Could you add config options to run any arbitrary commands after `deploy_challenge` and `clean_challenge`?
For me those commands would be:
```
/usr/bin/pdnsutil rectify-zone ${DOMAIN}
/usr/bin/pdns_control notify ${DOMAIN}
```
Maybe something like `PDNS_NOTIFY="..."`.

**Comment by jangrewe** [comment]
Maybe this could also be done via the API, with a `PUT` to `/api/v1/servers/:server_id/zones/:zone_id/notify`? I'm not sure if that's sufficient, though, as the PDNS API docs state that the "rectification" for changes made through the API isn't implemented yet.

**Comment by silkeh** [comment]
Hmm, if SOA-EDIT has been configured your master *should* pick up on the changed serial and send a notification quite quickly.

For running additional commands a wrapper script seems like a better solution to me than adding a hook to this hook.

I will look into implementing the notification API somewhere in the next few weeks.

**Comment by jangrewe** [comment]
I've added the `SOA-EDIT-API` domainmetada rows for my domains, so at least the serial number gets updated automatically now, and then added an API call that force an immediate NOTIFY, as there was quite some delay without it - this seems to work well now!
```
  # Perform requests
  for zone in "${!requests[@]}"; do
    request "PATCH" "${url}/${zone}" '{"rrsets": ['"${requests[${zone}]}"']}'
    request "PUT" "${url}/${zone}/notify" ''
  done
```

**Comment by silkeh** [comment]
#14 has been merged, thanks again!

**Comment by jangrewe** [comment]
Thanks! =)
