### ISSUE TITLE
dns-01 challenge error

### ISSUE THREAD

**Issue by imp1sh** [silkeh/pdns_api.sh#27]
Hi,

when I want to create a certificate I get this error:
```
rproxy:~# dehydrated -c -x
# INFO: Using main config file /etc/dehydrated/config
# INFO: Running /usr/local/bin/dehydrated as nginx/nginx
# INFO: Using main config file /etc/dehydrated/config
Processing gosix.lpv4.net
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Jun  6 12:26:27 2020 GMT Certificate will not expire
(Longer than 30 days). Ignoring because renew was forced!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for gosix.lpv4.net
 + 1 pending challenge(s)
 + Deploying challenge tokens...
 + Responding to challenge for gosix.lpv4.net authorization...
 + Cleaning challenge tokens...
 + Challenge validation has failed :(
ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "dns-01",
  "status": "invalid",
  "error": {
    "type": "urn:ietf:params:acme:error:dns",
    "detail": "DNS problem: NXDOMAIN looking up TXT for _acme-challenge.gosix.lpv4.net - check that a DNS record exists for this domain",
    "status": 400
  },
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/3257263957/uPpWfg",
  "token": "A1XG3Q5yWhxL7Quowe8x--IEzcfOAjO2tSojOOVqa-c"
})
```

The records are there:

```
host -t TXT _acme-challenge.gosix.lpv4.net ns0.gosix.net;  host -t TXT _acme-challenge.gosix.lpv4.net ns1.gosix.net
Using domain server:
Name: ns0.gosix.net
Address: 2a00:fe0:3f:3::5#53
Aliases: 

_acme-challenge.gosix.lpv4.net descriptive text "7hb-hbm45XpSTMXUOqf-w1glDCnA4GvJCZjc2SthmL0"
Using domain server:
Name: ns1.gosix.net
Address: 2001:4dd0:28d4:5000::10#53
Aliases: 

_acme-challenge.gosix.lpv4.net descriptive text "7hb-hbm45XpSTMXUOqf-w1glDCnA4GvJCZjc2SthmL0"
```

This is my dehydrated config:

```
PDNS_HOST=http://ns0.gosix.net:8081
PDNS_KEY=myveryownsecret
PDNS_VERSION=1
PDNS_WAIT=20
PDNS_NO_NOTIFY=yes
HOOK="/etc/dehydrated/basedir/pdns_api.sh"
HOOK_CHAIN="yes"
DEHYDRATED_USER=nginx
DEHYDRATED_GROUP=nginx
CA="https://acme-v02.api.letsencrypt.org/directory"
CHALLENGETYPE="dns-01"
BASEDIR=/etc/dehydrated/basedir
```

When I try staging CA it's working though.

**Comment by silkeh** [comment]
Thanks for the report, can you run the following?
```
env DEBUG=true dehydrated -c -x
```

PS: Use triple backticks (` ``` `) for code blocks

**Comment by edo1** [comment]
Did
```
host -t TXT _acme-challenge.gosix.lpv4.net 8.8.8.8
```
return the same?

**Comment by imp1sh** [comment]
Yes, it also returns the correct TXT record:
`host -t TXT _acme-challenge.gosix.lpv4.net 8.8.8.8
Using domain server:
Name: 8.8.8.8
Address: 8.8.8.8#53
Aliases: 

_acme-challenge.gosix.lpv4.net descriptive text "NW4OY9Kf6rp5PoN_toVRdQL4-1YNwuLhm07Y3Ejva_U"
`
With debug set the output is not different:
´´´env DEBUG=true dehydrated -c -x
# INFO: Using main config file /etc/dehydrated/config
# INFO: Running /usr/local/bin/dehydrated as nginx/nginx
# INFO: Using main config file /etc/dehydrated/config
Processing gosix.lpv4.net
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Jun  6 12:26:27 2020 GMT Certificate will not expire
(Longer than 30 days). Ignoring because renew was forced!
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 1 authorizations URLs from the CA
 + Handling authorization for gosix.lpv4.net
 + 1 pending challenge(s)
 + Deploying challenge tokens...
 + Responding to challenge for gosix.lpv4.net authorization...

 + Cleaning challenge tokens...
 + Challenge validation has failed :(
ERROR: Challenge is invalid! (returned: invalid) (result: {
  "type": "dns-01",
  "status": "invalid",
  "error": {
    "type": "urn:ietf:params:acme:error:dns",
    "detail": "During secondary validation: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.gosix.lpv4.net - check that a DNS record exists for this domain",
    "status": 400
  },
  "url": "https://acme-v02.api.letsencrypt.org/acme/chall-v3/3261693702/jc05tA",
  "token": "PrXzW5QY_4ynH6nErx_7T3DY_WIdxwi6glzasWxK2UA",
  "validationRecord": [
    {
      "hostname": "gosix.lpv4.net"
    }
  ]
})
´´´

**Comment by silkeh** [comment]
> Yes, it also returns the correct TXT record:

If the TXT record exists everywhere, that probably means that the hook is working correctly. No idea why it wouldn't work though.

How long does it take for your nameservers to be in sync? Why do you have `PDNS_NO_NOTIFY=no` (that disables a quick notification)?

> With debug set the output is not different

Are you running the latest master? Does adding `DEBUG=true` to your config work?

**Comment by imp1sh** [comment]
DEBUG=true in config works.
Don't know why I set PDNS_NO_NOTIFY  to yes. Eversince I set it to no, requesting certificates seem to work flawlessly.
