### ISSUE TITLE
Email Notify afterdeployment

### ISSUE THREAD

**Issue by ruben-herold** [silkeh/pdns_api.sh#32]
hi,

I want implement that we got an email after each successful deployed certificate.
In the code I found:

deploy_cert() {
  if [[ -n "${PDNS_DEPLOY_CERT_HOOK:-}" ]]; then
    ${PDNS_DEPLOY_CERT_HOOK}
  fi
}

I found nothing in the documentation about it.  A simple PDNS_DEPLOY_CERT_HOOK='echo "new certificate for ${1}" |  mail -s "new certificate for ${1}" test@test.com' did not work

**Comment by alainwolf** [comment]
Since pdns.api.sh is already a hook plugin of dehydrated but made solely for handling the DNS API, why not use the well documented hook infrastructure of dehydrated itself?

<https://github.com/dehydrated-io/dehydrated/blob/master/docs/examples/hook.sh>

**Comment by silkeh** [comment]
> Thx I did something similar but in pdns_api.sh. But we I like the idea from PDNS_DEPLOY_CERT_HOOK so could you think to document and extend it?

The hooks are now documented in the README, including their limitations.

> Since pdns.api.sh is already a hook plugin of dehydrated but made solely for handling the DNS API, why not use the well documented hook infrastructure of dehydrated itself?

This is definitely better, and I have included this in the README.
