### ISSUE TITLE
Config not found

### ISSUE THREAD

**Issue by jakob42** [silkeh/pdns_api.sh#8]
Hi,

I've got the problem that the pdns_hook cannot find it's config. It seems like $CONFIG is already set and thats why it doesn't load the config from the usual places (for me right next to the hook script).

I added `CONFIG=""` in line 26 below `DIR="$(dirname "$0")"`, which solved it for me, but I'm not sure what other repercussions it might have and maybe somebody else has the same problem.

dehydrated.conf:
```
CHALLENGETYPE="dns-01"
CERTDIR="/home/dehydrated/etc/certs"
DOMAINS_TXT="${CERTDIR}/../domains.txt"
ACCOUNTDIR="${CERTDIR}/../accounts"
HOOK=/home/dehydrated/pdns_api_hook/pdns_api.sh
HOOK_CHAIN="yes"
CONTACT_EMAIL=my@email
```
pdns_api config
```
HOST=pdnsserver
PORT=8081
KEY=API_key
WAIT=60
```

**Comment by silkeh** [comment]
If `$CONFIG` is already set, what is it set to?

**Comment by jakob42** [comment]
It is set to my dehydrated.conf, adding the pdns settings there seems to work. Just not sure if it is supposed to be like that (since the config isn't prefixed and could collide with dehydrated settings). But it works for me like that, so feel free to close and sorry for the noise.

**Comment by silkeh** [comment]
The original idea was that it could either be set in the dehydrated config or a separate config file. The latter doesn't work if `$CONFIG` is set.

You are right in that the variables should be prefixed, I will add them for the next release.

I will keep this issue open to remind me to think about the configuration. Thanks for reporting!
